version: "3.8"

services:
  backend:
    container_name: onfly_api
    # restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    networks: 
      - laranet
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: onfly_db
    # restart: always
    env_file:
      - .env
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks: 
      - laranet

networks: 
  laranet:
    driver: bridge